//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class tblCustomer
    {
        public tblCustomer()
        {
            this.tblCarts = new HashSet<tblCart>();
        }
    
        public int CusId { get; set; }

        public string CustName { get; set; }
        public string Addess { get; set; }
        public string PhoneNo { get; set; }
        public string EmailId { get; set; }
        public string UserId { get; set; }
        public string Password { get; set; }
    
        public virtual ICollection<tblCart> tblCarts { get; set; }
    }
}
