//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    public partial class tblCart
    {
        public int CartId { get; set; }
        public Nullable<int> CusId { get; set; }
        public Nullable<int> ModelId { get; set; }
        [Display(Name="Order Date")]
        public Nullable<System.DateTime> PurcharseDate { get; set; }
    
        public virtual tblCustomer tblCustomer { get; set; }
        public virtual tblModel tblModel { get; set; }
    }
}
