//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblModel
    {
        public tblModel()
        {
            this.tblCarts = new HashSet<tblCart>();
        }
    
        public int ModelId { get; set; }
        public string ModelName { get; set; }
        public string ModelImagePath { get; set; }
        public Nullable<bool> IsAvailable { get; set; }
        public Nullable<int> BrandId { get; set; }
        public Nullable<int> TypeId { get; set; }
        public Nullable<float> Price { get; set; }
        public Nullable<int> DiscountId { get; set; }
        public Nullable<int> StockId { get; set; }
        public virtual tblBrand tblBrand { get; set; }
        public virtual ICollection<tblCart> tblCarts { get; set; }
        public virtual tblDiscount tblDiscount { get; set; }
        public virtual tblStock tblStock { get; set; }
        public virtual tblType tblType { get; set; }
    }
}
